name: Is H5P library updated
description: Checks H5P library versions to see if the current branch is ahead of the main branch
author: boyum

branding:
  icon: package
  color: blue

inputs:
  github-token:
    required: false
    description: GITHUB_TOKEN or a repo scoped PAT
    default: ${{ github.token }}

  fail-if-not-ahead:
    required: false
    description: Fail this step if the current branch's version is not ahead of the main branch's version
    default: "false"

  working-directory:
    required: false
    description: The working directory to run the command in
    default: "."

outputs:
  is-ahead:
    description: True if the current branch's version is ahead of the main branch's version

  are-equal:
    description: True if the current branch's version and the main branch's versions are equal

  is-behind:
    description: True if the current branch's version is behind the main branch's version

  current-version:
    description: The current version as a JSON string with `majorVersion`, `minorVersion`, and `patchVersion` properties

  main-version:
    description: The main version as a JSON string with `majorVersion`, `minorVersion`, and `patchVersion` properties

  current-version-formatted:
    description: The current version as a string on the format `vx.y.z`

  main-version-formatted:
    description: The main version as a string on the format `vx.y.z`

runs:
  using: node20
  main: dist/index.js
